name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
          install-dependencies: true
      - name: Run tests (headless)
        run: mvn -B -Dheadless=true clean test
